env: dev

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: SERVER-GATEWAY

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

zuul:
  routes:
    sercer-oauth:
      path: /oauth/**
      serviceId: sercer-oauth
    module-user:
      path: /user/**
      serviceId: module-user
    module-product:
      path: /product/**
      serviceId: module-product
    module-common:
      path: /common/**
      serviceId: module-common



#排除某些路由
#  ignored-patterns:
#    - /shop/cloud/module/user/listForOrder
