env: dev

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: SERVER-GATEWAY

zuul:
  sensitive-headers: Cookie,Set-Cookie,Authorization
  routes:
    module-user:
      path: /user/**
      serviceId: module-user
    module-product:
      path: /product/**
      serviceId: module-product
    module-common:
      path: /common/**
      serviceId: module-common

datasource:
  ip: 127.0.0.1
  port: 3306
  database: shop
  username: root
  password: 635521736


#排除某些路由
#  ignored-patterns:
#    - /shop/cloud/module/user/listForOrder
