env: dev

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: SERVER-GATEWAY

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

zuul:
  routes:
    module-user:
      path: /user/**
    server-security:
      path: /security/**
    module-product:
      path: /product/**
    module-common:
      path: /common/**



#排除某些路由
#  ignored-patterns:
#    - /shop/cloud/module/user/listForOrder
