env: dev

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: SERVER-GATEWAY

zuul:
  sensitive-headers: Cookie,Set-Cookie,Authorization
  routes:
    module-user:
      path: /shop/cloud/module/user/**
      serviceId: module-user
    module-product:
      path: /shop/cloud/module/product/**
      serviceId: module-product
    module-common:
      path: /shop/cloud/module/common/**
      serviceId: module-common

#排除某些路由
#  ignored-patterns:
#    - /shop/cloud/module/user/listForOrder
